name: "Deploy BredaP21"

on: 
  push:
    branches: ["main"]

jobs:
  deploy-actionsBredaP21:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hola Mundo"
    - run: echo "Correr Migraciones"
    - run: echo "Generar binario"
    - run: echo "Publicar Version"